In [ ]:
import numpy as np
arr= np.arange(1,101)
arr_2d= arr.reshape(10,10)
print(arr)
print(arr_2d)
# Sum of each row
row_sum= np.sum(arr_2d, axis=1)
# Maximum sum
max_sum= np.argmax(row_sum)
# Minimum sum
min_sum= np.argmin(row_sum)
print(row_sum)
print(max_sum)
print(min_sum)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[ 55 155 255 355 455 555 655 755 855 955]
9
0


In [ ]:
import numpy as np
arr_2d= np.random.rand(5,5)
print(arr_2d)
last_colum= np.mean(arr_2d[:, -1])
arr_2d[:, -1]= last_colum
print(arr_2d)


[[0.8962175  0.20820083 0.06979606 0.35015626 0.61778009]
 [0.50131576 0.27969534 0.22855454 0.30482523 0.21959007]
 [0.15266507 0.24883966 0.28778318 0.2591587  0.40947095]
 [0.01519999 0.49622117 0.53128946 0.73293682 0.83362981]
 [0.19014544 0.83946444 0.92931486 0.33234396 0.8271213 ]]
[[0.8962175  0.20820083 0.06979606 0.35015626 0.58151844]
 [0.50131576 0.27969534 0.22855454 0.30482523 0.58151844]
 [0.15266507 0.24883966 0.28778318 0.2591587  0.58151844]
 [0.01519999 0.49622117 0.53128946 0.73293682 0.58151844]
 [0.19014544 0.83946444 0.92931486 0.33234396 0.58151844]]


In [ ]:
# 2d arry with (3,5) random normal shape
import numpy as np
arr_2d= np.random.normal( size= (3,5))
print(arr_2d)
# Mean, Median and Standard deviation of array
mean= np.mean(arr_2d)
median= np.median(arr_2d)
std_dev= np.std(arr_2d)
print(mean)
print(median)
print(std_dev)
# Maxiumum and Minimum value of array
max_value= np.max(arr_2d)
min_value= np.min(arr_2d)
print(max_value)
print(min_value)
#  Maxiumum and Minimum position of array
max_position= np.argmax(arr_2d)
min_position= np.argmin(arr_2d)
print(max_position)
print(min_position)





[[-0.5082831  -0.12165451  0.71524206  1.13112996  2.71202496]
 [ 0.50810248  0.44076014 -1.09247576 -0.71945243 -1.47145549]
 [ 1.05911401  0.78223577  2.22635579 -0.91796979 -1.16003426]]
0.23890932147383367
0.4407601370976226
1.2047254044376114
2.712024957622594
-1.4714554875263717
4
9


In [ ]:
import numpy as np
# Create (4,4) matrix
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
x= arr.reshape(4,4)
print(x)
Extrac_rows= x[1:3, :]
print(Extrac_rows)
matrix= Extrac_rows[:, 1:3]
print(matrix)
for row in matrix:
  for element in row:
    print(element**2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7]
 [10 11]]
36
49
100
121
